<div class="container-fluid" fc-website-creator data-rest-url='/rs/website.json'>
	<div class="row"><div class="col-md-4 col-md-offset-8">
		<button type='button' class='btn btn-primary' ng-click="onSave()">Create New Website</button>
	</div></div>
	<div class="row"><div class='col-md-8'><form name='creatorForm' novalidate>
		<div class="form-group">
			<label for="uniqueSubdomain" class="control-label col-sm-2">subdomain name:</label>
			<div class="col-sm-10">
				<input id="uniqueSubdomain" name="uniqueSubdomain" class="form-control" placeholder="unique subdmain name" ng-model="data.uniqueSubdomain" type="text" ng-minlength="5" required>
				<p ng-show="creatorForm.uniqueSubdomain.$error.minlength" class="help-block">at least five charaters are required!</p>
				<p ng-show='creatorForm.uniqueSubdomain.$error.required' class='help-block'>subdomain name is required!</p>									
			</div>
		</div>
		<div class="form-group">
			<label for="label" class="control-label col-sm-2">label:</label>
			<div class="col-sm-10">
				<input id="label" name="label" class="form-control" placeholder="label" ng-model="data.label" type="text" ng-minlength="2" required>
				<p ng-show="creatorForm.label.$error.minlength" class="help-block">at least five charaters are required!</p>
				<p ng-show='creatorForm.label.$error.required' class='help-block'>label is required!</p>									
			</div>
		</div>
	</form></div></div>
</div>

<script src='<?php echo $this->path('account')?>/website/ng/website.js'></script>
<script>
	var adminApp = angular.module('adminApp', ['fcClientModule']);
</script>