<div class='container-fluid' fc-website-editor data-id='<?php echo $this->id?>'><div class='row'>
	<div class='page-actions'>
		<h3>Website Edit: {{::formData.label}}</h3>
		<button type='button' ng-click='onConfirm()' class='btn btn-primary pull-right'>Confirm</button>
	</div>
	<div>
	{{formData.label}} - globalSiteId : {{::formData.globalSiteId}}
	</div>
	<div>
	created: {{::formData.created.date}}
	</div>
	<div>
	expires on:{{::formData.expireDate.date}}
	</div>
	
	
	<form name="websiteForm" class="form-horizontal" novalidate>
		<div class="form-group">
			<label for="label" class="control-label col-md-2">Label:</label>
			<div class="col-md-10">
				<input id="label" name="label" class="form-control" placeholder="Website Label" ng-model="formData.label" type="text" />
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-md-2">Domain names:</label>
			<div class="col-md-10">
				<ul class='increament-list'>
					<li ng-class='{true: "default-domain", false: ""}[domain.isDefault]' ng-repeat='(key, domain) in formData.domains'>
						{{domain.domainName}}
						<div class='clickable pull-right' ng-click='onRemoveDomain(domain.id)' ng-if='!domain.isDefault'>
							<i class='fa fa-minus-circle icon-danger'></i>
						</div>
						<div class='clickable pull-right' ng-click='onToggleDomainActive(domain.id, domain.isActive)' ng-if='domain.isDefault'>
							<i ng-show='domain.isActive' class='fa fa-toggle-on icon-active'></i>
							<i ng-hide='domain.isActive' class='fa fa-toggle-off'></i>
						</div>
					</li>
					<li class='insert-new'>
						<button ng-hide='disp.addDomainForm' type='button' class='btn btn-primary btn-xs' ng-click='onAddDomain()'>add new domain</button>
						<div ng-show='disp.addDomainForm' class='row'>
							<div class='col-sm-4'>
								<input id="domain-name" name="domainName" class="form-control input-sm" placeholder="Domain Name" ng-model="domainData.domainName" type="text" />
							</div>
							<div class='col-sm-2'>
								<button type="button" class='btn btn-success btn-sm' ng-click='onConfirmDomain()'>Confirm</button>
							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</form>
</div></div>

<script src='<?php echo $this->path('account')?>/website/ng/website.js'></script>
<script>
	appRequiredModules.push('fcWebsiteModule');
</script>