<div class="container-fluid" fc-client-creator data-rest-url='/admrs/rs-client.json' data-website-id='<?php echo $this->websiteId?>'>
	<div class="row"><div class="col-md-4 col-md-offset-8">
		
	</div></div>
	<div class="row"><div class='col-md-8'><form name='clientCreatorForm' class='form-horizontal' novalidate>
		<div class="form-group">
			<label for="companyName" class="control-label col-sm-2">Company Name公司名字:</label>
			<div class="col-sm-10">
				<input id="companyName" name="companyName" class="form-control" placeholder="company name" ng-model="formData.companyName" ng-disabled='disp.bindCompany' type="text" ng-minlength="2" required>
				<p ng-show="clientCreatorForm.companyName.$error.minlength" class="help-block">at least five charaters are required!</p>
				<p ng-show='clientCreatorForm.companyName.$error.required' class='help-block'>company name is required!</p>									
			</div>
		</div>
		<div class='form-group'>
			<div class="col-sm-10 col-sm-offset-2">
				<label for='bindCompanyCheck'><input id='bindCompanyCheck' type='checkbox' ng-model='bindCompanyCheck' ng-click='onBindCompany()' /> Bind Company</label>
			</div>
		</div>
		<div class="form-group" ng-show='disp.bindCompany'>
			<label for="companySelector" class="control-label col-sm-2">Select Company:</label>
			<div class="col-sm-4">
				<select class='form-control' ng-model='formData.companyId' ng-change='onChangeSelect()' ng-options='item.id as item.label for item in selectOptions'></select>
				<br />
				id: {{formData.companyId}}
			</div>
			<div class="col-sm-6">
				<input class="form-control" placeholder="search by company name" ng-model="searchData" ng-keyup='onSearch()' type="text" />
			</div>
		</div>
		<button type='button' class='btn btn-primary' ng-click="onSave()">Create New Client</button>
	</form></div></div>
</div>

<script src='<?php echo $this->path('account')?>/client/ng/client.js'></script>
<script>
	appRequiredModules.push('fcClientModule');
</script>