<div class="container-fluid" fc-client-creator data-rest-url='/admrs/rs-client.json' data-website-id='<?php echo $this->websiteId?>'>
	<div class="row"><div class="col-md-4 col-md-offset-8">
		<button type='button' class='btn btn-primary' ng-click="onSave()">Create New Client</button>
	</div></div>
	<div class="row"><div class='col-md-8'><form name='clientCreatorForm' class='form-horizontal' novalidate>
		<div class="form-group">
			<label for="companyName" class="control-label col-sm-2">companyName:</label>
			<div class="col-sm-10">
				<input id="companyName" name="companyName" class="form-control" placeholder="company name" ng-model="clientData.companyName" type="text" ng-minlength="2" required>
				<p ng-show="clientCreatorForm.companyName.$error.minlength" class="help-block">at least five charaters are required!</p>
				<p ng-show='clientCreatorForm.companyName.$error.required' class='help-block'>company name is required!</p>									
			</div>
		</div>
	</form></div></div>
</div>

<script src='<?php echo $this->path('account')?>/client/ng/client.js'></script>
<script>
	var adminApp = angular.module('adminApp', ['fcClientModule']);
</script>