<div class='data-list' fc-data-list data-url="<?php echo $this->url('admrs/restroutes', array('controller' => 'rs-client'), true)?>" >
	<div class='page-actions'>
		<h3>Client List</h3>
		<a class='btn btn-primary pull-right' href='/admin/client/create'><i class='fa fa-plus'></i> Create New</a>
	</div>
	<div ng-controller = "searchController" ng-init = "init('articleQueryObj')" class="dataSerach row">
		<form class="form-horizontal" role="form">
			
		</form>
	</div>
	<table class='table table-bordered table-hover table-striped'>
		<thead class='datalist-head'>
			<tr class='title-row'>
				<th class="text-center" fc-filter-sort width='600' data-sindex="label">
					<strong>Client Name</strong>
					<i ng-if="sortModel.isActive" ng-class="{true:'fa fa-caret-up', false:'fa fa-caret-down'}[sortModel.sOrder > 0]"></i>
				</th>
			</tr>
		</thead>
		<tbody class='datalist-body  text-center'>
			<tr ng-repeat="(key, doc) in dataArr.data">
				<td class="text-left"><a href='/admin/client/edit/id/{{key}}'>{{::doc.companyName}}</a></td>
			</tr>
		</tbody>
		<tfoot ng-if="disp.tfoot">
			<tr class='paginator-row'>
				<td id='datalist-paginator'>
					<div>
						<span>page:{{dataArr.currentPage}}/{{dataArr.maxPage}}</span>
						<a ng-if="disp.prev" href="javascript:;" ng-click="onPage(dataArr.currentPage-1)">上一页</a>
						<a ng-if="disp.next" href="javascript:;" ng-click="onPage(dataArr.currentPage+1)">下一页</a>
						<select	style="width: 80px;" class="form-control" ng-model="dataArr.currentPage" ng-change="onPage(dataArr.currentPage)" 
								ng-options="page for page in dataArr.pageOption"></select>
					</div>
					<div>总记录:{{dataArr.dataSize}}</div>
				</td>
			</tr>
		</tfoot>
	</table>
</div>

<script>
	appRequiredModules.push('fcDataModule');
</script>
<script type="text/javascript" src="<?php echo $this->path('common')?>/ng/data-list.js"></script>