<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
	<link rel="stylesheet" href="http://lib.eo.test/fucms.account/style/reset.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="http://lib.eo.test/fucms.account/style/sp.css" type="text/css" media="screen, projection">
	<script type="text/javascript" src="http://misc.fucms.com/admin-misc/js/jquery-2.0.3.min.js"></script>
</head>
<body>
<?php echo $this->content; ?>
</body>
</html>