<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentServerHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['ipAddress'])) {
            $value = $data['ipAddress'];
            $return = (string) $value;
            $this->class->reflFields['ipAddress']->setValue($document, $return);
            $hydratedData['ipAddress'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['internalIpAddress'])) {
            $value = $data['internalIpAddress'];
            $return = (string) $value;
            $this->class->reflFields['internalIpAddress']->setValue($document, $return);
            $hydratedData['internalIpAddress'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['activeWebsiteLimit'])) {
            $value = $data['activeWebsiteLimit'];
            $return = (int) $value;
            $this->class->reflFields['activeWebsiteLimit']->setValue($document, $return);
            $hydratedData['activeWebsiteLimit'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['activeWebsiteCount'])) {
            $value = $data['activeWebsiteCount'];
            $return = (int) $value;
            $this->class->reflFields['activeWebsiteCount']->setValue($document, $return);
            $hydratedData['activeWebsiteCount'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['version'])) {
            $value = $data['version'];
            $return = (float) $value;
            $this->class->reflFields['version']->setValue($document, $return);
            $hydratedData['version'] = $return;
        }
        return $hydratedData;
    }
}