<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ClientDocumentPaymentHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['clientId'])) {
            $value = $data['clientId'];
            $return = (string) $value;
            $this->class->reflFields['clientId']->setValue($document, $return);
            $hydratedData['clientId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['purpose'])) {
            $value = $data['purpose'];
            $return = (string) $value;
            $this->class->reflFields['purpose']->setValue($document, $return);
            $hydratedData['purpose'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['totalAmount'])) {
            $value = $data['totalAmount'];
            $return = (int) $value;
            $this->class->reflFields['totalAmount']->setValue($document, $return);
            $hydratedData['totalAmount'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['amountSettled'])) {
            $value = $data['amountSettled'];
            $return = (int) $value;
            $this->class->reflFields['amountSettled']->setValue($document, $return);
            $hydratedData['amountSettled'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['amountOverdue'])) {
            $value = $data['amountOverdue'];
            $return = (int) $value;
            $this->class->reflFields['amountOverdue']->setValue($document, $return);
            $hydratedData['amountOverdue'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['amountUncollectible'])) {
            $value = $data['amountUncollectible'];
            $return = (int) $value;
            $this->class->reflFields['amountUncollectible']->setValue($document, $return);
            $hydratedData['amountUncollectible'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['settlements']) ? $data['settlements'] : null;
        $return = new \Doctrine\ODM\MongoDB\PersistentCollection(new \Doctrine\Common\Collections\ArrayCollection(), $this->dm, $this->unitOfWork, '$');
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['settlements']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['settlements']->setValue($document, $return);
        $hydratedData['settlements'] = $return;

        /** @Field(type="string") */
        if (isset($data['status'])) {
            $value = $data['status'];
            $return = (string) $value;
            $this->class->reflFields['status']->setValue($document, $return);
            $hydratedData['status'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['created'])) {
            $value = $data['created'];
            if ($value instanceof \MongoDate) { $date = new \DateTime(); $date->setTimestamp($value->sec); $return = $date; } else { $return = new \DateTime($value); }
            $this->class->reflFields['created']->setValue($document, clone $return);
            $hydratedData['created'] = $return;
        }
        return $hydratedData;
    }
}