<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('method', 'post');
	$form->setAttribute('class', 'login-form');
?>
<?php if(!is_null($this->errorMsg)) {?>
<div class='error-msg'>
	<?php echo $this->errorMsg ?>
</div>
<?php }?>
<div class='login-page'>
	<div class="login-logo"></div>
	<?php echo $this->form()->openTag($form); ?>
		<div class='element-row'>
			<div class='login-input login-name'><?php echo $this->formRow($form->get('loginName'))?></div>
		</div>
		<div class='element-row'>
			<div class='login-input password'><?php echo $this->formRow($form->get('password'))?></div>
		</div>
		<div class='element-row'>
			<?php echo $this->formRow($form->get('login-button'))?>
			<br />
			<a class='links' href='/sp/register'>注册新用户</a>
			<a class='links' href='/sp/register'>找回密码</a>
		</div>
	<?php echo $this->form()->closeTag(); ?>
</div>

<script type="text/javascript" src="<?php echo $this->path('compact')?>/acc/_sp.js"></script>