<div class='login-form-div'>
	<div class="login-form">
		<h3 class="title"><?php echo $this->webSiteName?></h3>
		<form action='' method='post'>
			<dl>
				<dt>
					<i class="fi-torso" style="font-size: 25px; width: 20px;"></i>
				</dt>
				<dd>
					<input id="login" onFocus="borderColor(this,'#008cba')"
						onBlur="borderColor(this,'#eee')" type='text' name='loginName'
						value='' />
				</dd>
			</dl>
			<div id="error" class="error-message"><?php echo $this->info?></div>
			<dl>
				<dt>
					<i class="fi-key" style="font-size: 25px; width: 25px;"></i>
				</dt>
				<dd>
					<input onFocus="borderColor(this,'#008cba')"
						onBlur="borderColor(this,'#eee')" type='password' name='password'
						value='' />
				</dd>
			</dl>
			<input class="postbtn" type='submit' name='submit' value='进入管理' />
		</form>
	</div>
</div>

<script>
	function borderColor(e,color){
		e.parentNode.parentNode.style.borderColor=color;
	}
	var info="<?php echo $this->info?>";
	if(info){
		var obj=document.getElementById("error"),
			login=document.getElementById("login");
		login.focus();
		setTimeout(function (){
			obj.style.display="none";
			},4000);
	}

</script>